sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t lehoai257/docker-reactapp -f DockerFile.dev .

script:
  - docker run -e CI=true lehoai257/docker-reactapp npm run test
