sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t lehoai257/docker-reactpp -f Dockerfile.dev .

script:
  - docker run -e CI=true lehoai257/docker-reactpp npm run test
